RoleModel/optics

- src/core/dynamic_color_engine.scss
- src/theme/dark_theme.scss
Dark mode was redefining the luminosity scale and the making numbers point to something on the scale that was not actually the same number. E.G. it would point to luminosity-10 which actually meant 5% luminosity.
> Change luminosity scale

- README.md
- src/core/tokens/dark_mode_tokens.scss
- src/theme/rolemodel_theme.scss
#36 
This addresses a part of the above-mentioned issue. In applications that do not have a dark mode, or need to temporarily disable it, there is no easy way to do that.
The current solution is to selectively import everything the `rolemodel-design-system.scss` file imports and then remove the one line that imports the dark mode tokens.
This solution allows an application to disable dark mode by setting a data attribute on the `html` element.
> [GHI #36] Add ability to disable dark mode

- src/components/icon.scss
If an application uses a compiler other than webpack. I.E. Dart Sass, when it gets to the material symbols import, it isn't smart enough to know to pull the .scss version of material symbols so we need to be explicit about it
> Specify scss for material symbols import

- package-lock.json
- package.json
- src/components/icon.scss
Once again... When you are not in a webpack compiling context, using a local version of the material symbols icons was not compiling properly.
> Material Symbols Update

- .github/pull_request_template.md
- build_token_json.js
The JSON formatting for exported tokens was very difficult to read
> fix formatting for exported json

- src/components/button.scss
https://github.com/RoleModel/rolemodel-design-system/issues/61
> [GHI #61] Button Icon with Size

- src/components/icon.scss
- src/stories/Icon.stories.js
- src/stories/Icon/Icon.js
- src/stories/Icon/Icon.mdx
https://github.com/RoleModel/rolemodel-design-system/issues/60
> [GHI #60] Use real token and fix default icon vertical alignment

- src/components/button.scss
- src/stories/Button/Button.mdx
https://github.com/RoleModel/rolemodel-design-system/issues/72
Not only was the initial implementation of the small breakpoint size adjustment not handling `btn--icon` correctly,
It was accidentally removed in https://github.com/RoleModel/rolemodel-design-system/pull/80/files
This PR adds it back and fixes previous bugs
> [GHI #72] button icon with breakpoints

- src/components/form.scss
- src/stories/Form/Form.js
- src/stories/Form/Form.mdx
- src/stories/FormGroup.stories.js
https://github.com/RoleModel/rolemodel-design-system/issues/40
Error messages don't wrap cleanly. Additionally, form group didn't take advantage of gap which required using padding or margin on the inner elements which led to occasional inconsistent spacing.
> [GHI #40] Form Group and error messages

- src/components/table.scss
- src/stories/Table.stories.js
- src/stories/Table/Table.js
- src/stories/Table/Table.mdx
#82 
Sticky header, fixed height:
Sticky footer, fixed height:
> [GHI #82] Table Enhancements

- src/components/card.scss
- src/core/utilities.scss
- src/stories/Card.stories.js
- src/stories/Card/Card.js
- src/stories/Card/Card.mdx
- src/stories/Shadow.stories.js
- src/stories/Shadow/Shadow.mdx
#96 
After a team discussion, we have opted to not add utilities and instead actually remove a few.
The line we have generally drawn is that utilities should be for layout and position, not for look and feel. Therefore, the font size and weight, and shadow utilities will be deprecated. This PR moves us more in line with that goal.
> [GHI #14] Standardize Utilities

- src/addons/tom-select.scss
#112 
The Tom Select Addon that provides styling for tom select that matches our system seems to make too many assumptions and usually needs to be further styled when pulled into an app.
> [GHI #112] Tom Select Revisited

- src/components/button.scss
- src/core/tokens/base_tokens.scss
#114 
Buttons are missing focus states that would be nice to add. Additionally, they make assumptions about font weight that probably need to be removed. Specifically the small button raises the font weight too much.
> [GHI #114] Buttons Revisited

- package-lock.json
- package.json
- src/components/form.scss
- src/core/tokens/base_tokens.scss
- src/stories/1_Introduction.stories.mdx
- src/stories/Form/Form.js
- src/stories/Select.stories.js
#126 
Select dropdowns inside of a flexible container result in the arrow overlapping the text.
Note: It still does clip the contents within the select if it's small enough but the arrow doesn't overlap strangely. I think this is an inherent limitation of styling select elements. Setting a min-width override if you absolutely need it is an option, but would be context driven.
> [GH #126] Select Bug

- .github/workflows/release-package.yml
- README.md
- package-lock.json
- package.json
#98 
We want to publish to both NPM and GHP to allow Optics to be used in conjunction with Private Repositories in GHP.
- ~~Have you run linters?~~
- ~~Have you run prettier?~~
- ~~Have you tried building the css?~~
- ~~Have you tried building storybook?~~
> [GHI #98] Deployment strategy

- package-lock.json
- package.json
- src/components/form.scss
`.form-control` has a grid style on it for positioning in a group (for alignment with label, hint, errors).
In cases where you want a styled input but not in a group (I.E. a calendar month or year dropdown), the input inherits grid styling from a parent and tries to align to in incorrectly.
> Form Group Refactor

- package-lock.json
- package.json
- src/components/form.scss
see issue #138 
CSS [SubGrid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Subgrid) would provide a much more elegant solution..
I can imagine a `.form-row` taking over for `.form-group` with it's own grid area.  So, given `.form-row > .form-group*n > .form-label+.form-control+.form-error` each label/control/error would occupy a grid-row with their respective siblings in neighboring `.form-groups`.  Alas
> prevent form-error from shifting form-group [fix #138]

- .github/release.yml
#142 
We want to add a clear labeling scheme for our releases. This allows us to auto generate release notes pre categorized.
- ~~Have you run linters?~~
- ~~Have you run prettier?~~
- ~~Have you tried building the css?~~
- ~~Have you tried building storybook?~~
Here is an example if we included every versions changes.
Note: Breaking Changes was moved to the top.
> [GHI #142] Release Template

- .github/workflows/publish-storybook.yml
- .storybook/documentation.scss
- src/stories/4_ScaleOverriding.stories.mdx
- src/stories/Font/Font.js
- src/stories/Font/FontFamily.mdx
- src/stories/Font/FontSize.mdx
- src/stories/Font/FontWeight.mdx
- src/stories/Font/LineHeight.mdx
- src/stories/FontFamily.stories.js
- src/stories/FontSize.stories.js
- src/stories/FontWeight.stories.js
- src/stories/LetterSpacing.stories.js
- src/stories/LineHeight.stories.js
#101 
In addition to adding the clarifying note,  we want to add documentation for all the typography related tokens that currently exist.
- ~~Have you run linters?~~
- ~~Have you run prettier?~~
- ~~Have you tried building the css?~~
> [GHI #101] Font and Line Height

- .github/workflows/publish-storybook.yml
With the addition of manually triggering the storybook publishing, I believe the workflow is not setting up everything it needs in order to accomplish it.
> Fix the storybook building

- src/components/button.scss
- src/components/button_group.scss
- src/stories/Badge/Badge.js
- src/stories/Button.stories.js
- src/stories/Button/Button.js
- src/stories/Button/Button.mdx
- src/stories/ButtonGroup.stories.js
- src/stories/ButtonGroup/ButtonGroup.js
- src/stories/ButtonGroup/ButtonGroup.mdx
[TR #12](https://trello.com/c/Z5R2MTzw)
Figma designs have been made and the current buttons do not match them.
> [TR#12] Button Revisions

- .storybook/documentation.scss
- src/components/confirm-dialog.scss
- src/components/index.scss
- src/stories/ConfirmDialog.stories.js
- src/stories/ConfirmDialog/ConfirmDialog.js
- src/stories/ConfirmDialog/ConfirmDialog.mdx
The dialog was designed in figma, but needed to be implemented.
> Add confirm dialog with documentation

- src/addons/tom-select.scss
- src/components/button.scss
- src/components/form.scss
- src/core/tokens/base_tokens.scss
- src/stories/Components/Button/Button.mdx
- src/stories/Tokens/EncodedImage.mdx
- src/stories/Tokens/Input/InputFocus.mdx
@zoopmaster pointed out that our focus state was too aggressive on buttons. Rather than show it on click or tab focus, we should show it only on tab (keyboard navigation) focus, but not on click.
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html
The intent of the focus ring is to replace the natural pointer interaction when not using a direct selection device, such as a mouse, touchpad, pen tablet, or trackball. When using a keyboard or assistive technology you need this visual indication on the screen because the user is not directly pointing to the control itself.
https://github.com/RoleModel/optics/assets/5957102/6ca6ae1b-1985-467a-921f-e95d97a24fad
> Button Focus Fix

- package-lock.json
- package.json
- src/addons/tom-select.scss
- src/stories/Overview/Addons.mdx
When this package is installed, it currently also installs Tom Select automatically, even if you are not using the add-on. I wanted to resolve this issue.
In order to fix this, two things needed to happen:
> Addon change

- package-lock.json
- src/components/alert.scss
- src/stories/Components/Alert/Alert.mdx
An issue that was noticed on a few projects was how the Rails convention for flash names was difficult to change and made it hard to work with the alert component.
> Alerts fix

- src/core/layout.scss
- src/core/tokens/base_tokens.scss
- src/core/utilities.scss
- src/stories/Tokens/Breakpoint.mdx
SCSS variables cannot be used in calc while CSS variables cannot be used in media queries.
In order to use breakpoint values for things like calculations or max widths, we want to add css variable version of the breakpoints  to prevent magic numbers and allow consistent sizing of things.
> Breakpoint continuity

- src/components/form.scss
@dallasbpeters noticed the Select form control was not using the correct background color. This was due to how the dropdown arrow was being applied.
If the background was changed, the select wouldn't match other inputs
Before
After
> Select control fix

- src/core/tokens/base_tokens.scss
- src/core/tokens/dark_mode_tokens.scss
[TR #140](https://trello.com/c/FIewEKNw/140-update-encoded-images-dropdown-arrow-to-reflect-figma-arrow-style)
We should update the --op-encoded-images-dropdown-arrow token value to reflect what is in figma
> [TR#140] Dropdown Encoded Image

- src/components/avatar.scss
- src/components/button.scss
- src/components/confirm-dialog.scss
- src/components/form.scss
- src/components/modal.scss
- src/components/switch.scss
- src/components/tab.scss
- src/components/tooltip.scss
- src/core/tokens/base_tokens.scss
- src/stories/Tokens/Opacity.mdx
[TR #137](https://trello.com/c/nRAf2fPR/137-add-global-opacity-tokens)
Things like disabled or potentially hover opacity are currently being duplicated in things like tab, avatar, and button.
These should be made consistent.
> [TR#137] Opacity Tokens

- src/components/accordion.scss
- src/components/avatar.scss
- src/components/confirm-dialog.scss
- src/components/modal.scss
- src/components/navbar.scss
- src/components/sidebar.scss
- src/components/spinner.scss
- src/components/switch.scss
- src/components/table.scss
- src/components/tooltip.scss
- src/core/tokens/base_tokens.scss
- src/stories/Components/Accordion/Accordion.mdx
- src/stories/Components/Button/Button.mdx
- src/stories/Components/ButtonGroup/ButtonGroup.mdx
- src/stories/Components/ConfirmDialog/ConfirmDialog.mdx
- src/stories/Components/Divider/Divider.mdx
- src/stories/Components/Form/Form.mdx
- src/stories/Components/Modal/Modal.mdx
- src/stories/Components/Navbar/Navbar.mdx
- src/stories/Components/Sidebar/Sidebar.mdx
- src/stories/Components/Spinner/Spinner.mdx
- src/stories/Components/Switch/Switch.mdx
- src/stories/Components/Table/Table.mdx
- src/stories/Components/Tooltip/Tooltip.mdx
- src/stories/Overview/ScaleOverriding.mdx
- src/stories/Tokens/Sizing.mdx
- src/stories/Tokens/Spacing.mdx
[TR #138](https://trello.com/c/Ye1eKd1m/138-add-size-scale)
Similar to the space scale, but instead of being for padding, margin, and gap, these would be for width and height.
For almost all cases (unless there is a good justification), sizes should be divisible by 4.
> [TR#138] Size Scale

- src/components/button.scss
- src/stories/Components/Button/Button.mdx
[TR #136](https://trello.com/c/0dsQb9qy/136-remove-no-border-warning-variant-modifier-combo)
This is not a combo designers recommend and should never be used. Our code shouldn’t allow for this.
The delete button is already preventing its combo in this regard so we should update Warning to do the same.
> [TR#136] Remove warning + no border state for button

- src/components/switch.scss
[TR #144](https://trello.com/c/puTaCcXF/144-firefox-does-not-hide-the-checkbox-even-if-size-is-explicitly-set-to-zero)
The checkbox was still visible on Firefox despite explicit size declarations. This hides it completely.
> [TR#144] Hide still-visible checkbox on Firefox

- src/core/tokens/base_tokens.scss
[TR#145](https://trello.com/c/tRhN8ZwW/145-transition-tooltip-token-was-missing)
`tooltip.scss` calls for `--op-transition-tooltip` but it was not in `base_tokens.scss`. This PR fixes that. 
~- [ ] Have you updated any usage of changed tokens?~
~- [ ] Have you updated the docs with any component changes?~
~- [ ] Have you updated the dependency graph with any component changes?~
~- [ ] Do you need to update the package version?~
> [TR#145] adds transition-tooltip to base_tokens

- src/components/switch.scss
[TR #148](https://trello.com/c/g79GpkR3/148-switch-control-shows-the-actual-checkbox-input-behind-the-switch-when-disabled)
The checkbox in the switch control is finicky and can’t be hidden entirely, so it appeared when we lower the opacity for the disabled state. This fixes this.
> [TR#148] Hide checkbox input when disabled

- src/components/form.scss
- src/stories/Components/Form/Input.stories.js
[TR #147](https://trello.com/c/YLEBlwc8/147-form-control-of-type-file)
@zoopmaster noticed that inputs with type set to file were not being styled correctly. This remedies that!
Before:
After:
> [TR#147] Sensible file input styles

- src/components/accordion.scss
A bug was discovered where Safari does not show accordions correctly.
Before:
After:
> Fix accordion arrow showing in safari

- src/addons/tom-select.scss
- src/components/card.scss
- src/components/confirm-dialog.scss
- src/components/divider.scss
- src/components/modal.scss
- src/components/side_panel.scss
- src/components/table.scss
- src/core/tokens/base_tokens.scss
- src/stories/Tokens/Border/BorderStroke.mdx
- src/stories/Tokens/Color/BorderColor.mdx
Fixes OP-145
The border color token did not match the pattern of other colors. This provides consistency
> [OP-145] --op-border-color rename

- src/components/avatar.scss
When an avatar was used inside a flex container, the width and height would get ignored and the avatar would squish
- ~~[ ] Have you updated any usage of changed tokens?
Before:
After:
> [OP-149] Fix Avatar Squish inside a flex container

- src/stories/Tokens/Typography/FontFamily.mdx
Some apps need more than one font. This explains the simple way to add some.
> [OP-148] Alternate Font Pattern

- src/components/tooltip.scss
- src/stories/Tokens/Color/ColorWithAlpha.mdx
Fixes OP-31 
The question of how to utilize alpha in our colors has come up so we want to provide some guidance on it.
> [OP-31] Alpha Color Documentation

- .storybook/documentation.scss
- src/stories/Components/Tooltip/Tooltip.mdx
Tooltips on Disabled buttons do not show up. We want to add some documentation for how to work around it.
> [OP-123] Tooltip on disabled Button

- src/components/form.scss
There is an issue with compound selectors that have a child under `::file-selector-button` in it. It breaks the whole selector
Due to how the file selector button is styled, if you put a child selector in the button global style, it will break it.
E.G. Always styling icons within buttons with a certain color
```css
%btn-global {
.material-symbols-outlined {
color: red;
}
}
// Output that is broken
.form-control[type=file]::file-selector-button .material-symbols-outlined,
.btn .material-symbols-outlined {
color: red;
}
```
Technically this is a breaking change though I suspect not many projects are styling the file selector button so it may not be an issue.
- ~~[ ] Have …
> [OP-25] Compound Selector with ::file-selector-button

- .storybook/documentation.scss
- src/recipes/aligned-header.scss
- src/stories/Recipes/AlignedHeader/AlignedHeader.js
- src/stories/Recipes/AlignedHeader/AlignedHeader.mdx
- src/stories/Recipes/AlignedHeader/AlignedHeader.stories.js
This is a problem that came up. The solution isn't a general component level solution, but having it as a recipe can help people if they do encounter it.
> [OP-150] Aligned Header Recipe

- src/components/button.scss
- src/components/button_group.scss
- src/stories/Components/Button/Button.mdx
- src/stories/Components/Button/Button.stories.js
- src/stories/Components/ButtonGroup/ButtonGroup.mdx
- src/stories/Components/ButtonGroup/ButtonGroup.stories.js
- src/stories/Components/ConfirmDialog/ConfirmDialog.js
From a semantic perspective, delete doesn't match other buttons. The original reason for the naming was to convey more intention when using it. `destructive` is just as semantic, but allows for broader use cases like closing an account (that may be recoverable)
> [OP-152] Rename btn-delete to btn-destructive

- src/stories/Components/Tab/Tab.js
This bug was caused by the recent reorganization of documentation revealing a hard-coded link in the tab example
> [OP-158] Fix tab link in docs

- src/stories/Overview/Addons.mdx
- src/stories/Overview/ScaleOverriding.mdx
- src/stories/Overview/Tokens.mdx
[TR #XXX]()
Resolve mistypes found within Addons.mdx ScaleOverriding.mdx and Tokens.mdx
If any UI changes need to be shown off, please add screenshots here.
> cleanup documentation on Addons.mdx ScaleOverriding.mdx and Tokens.mdx

- src/stories/Components/Avatar/Avatar.js
The current href link on the Avatar component is `components-avatar--docs` and the actual path is `content-components-avatar--docs`. The breaking difference being that `content` is missing.
> Fix href Link on Avatar Component

- src/components/icon.scss
According to recommendations here https://developers.google.com/fonts/docs/material_symbols#optimize_the_icon_font we should be using the display block option to prevent the icon text from rendering during load. See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for details on what this setting actually does.
> Improve icon font initial page load state

- .storybook/preview.scss
- src/core/tokens/base_tokens.scss
- src/stories/Tokens/Typography/Font.js
- src/stories/Tokens/Typography/FontFamily.mdx
- src/stories/Tokens/Typography/FontFamily.stories.js
The google font import for Noto Sans and Noto Serif was not including all the available axes for the variable fonts. This change allows for that and actually simplifies the font face file loaded from google and reduces the size of the payload.
Note: It isn't shown in the image, but the single request is loading both Noto Sans and Noto Serif
> [OP#168] Update the font import to use newer syntax

- src/components/form.scss
The color input showed the text cursor instead of pointer on hover. It should be the pointer since it opens the color picker menu.
> [OP#161] Use correct cursor for color input

- src/addons/panel.scss
- src/components/sidebar.scss
- src/core/tokens/base_tokens.scss
The sidebar was not using a z index which caused the navbar (if used in combination) was covering up the sidebar border.
> [OP#162] Use the correct z index for the sidebar

- src/stories/Tokens/Typography/FontFamily.mdx
Improving the documentation and adding instructions on how to use variable fonts.
> [OP#169] Variable Font Instructions

- .storybook/preview.scss
- package.json
- src/components/button.scss
- src/components/sidebar.scss
- src/core/tokens/base_tokens.scss
- src/stories/Components/Button/Button.mdx
- src/stories/Tokens/Breakpoint.mdx
- src/stories/Utilities/Container/Container.mdx
In an effort to reduce dependencies on SCSS features, we want to remove the `$breakpoint-...` SCSS variables. Media queries cannot use CSS variables and the spec for environment variables doesn't seem like it is moving anytime soon. https://drafts.csswg.org/css-env-1/
- ~[ ] Have you updated the dependency graph with any component changes?~
> CCC-44 Breakpoint Variables

- package.json
- src/components/table.css
- src/stories/Components/Table/Table.js
- src/stories/Components/Table/Table.mdx
With the move toward plain css, the Table styling needs to be converted to CSS with a strict adherence to the BEM structure.
- ~[ ] Have you updated any usage of changed tokens?~
- ~[ ] Have you updated the dependency graph with any component changes?~
> OP-189 Refactor Table

- src/stories/Components/Sidebar/Sidebar.js
- src/stories/Components/Sidebar/Sidebar.mdx
- src/stories/Components/Sidebar/Sidebar.stories.js
Remove responsive references and add javascript snippet for how to achieve
> Add details to sidebar documentation

- .storybook/preview.css
- src/components/accordion.css
- src/core/tokens/base_tokens.css
- src/stories/Components/Accordion/Accordion.js
- src/stories/Components/Accordion/Accordion.mdx
- src/stories/Components/Accordion/Accordion.stories.js
- src/stories/Components/Icon/Icon.js
- src/stories/Tokens/Animation/Animation.stories.js
With the following features gaining support in some browsers and having a graceful fallback (to existing behavior) for browsers that don't support it, animated accordions are now possible.
* https://developer.mozilla.org/en-US/docs/Web/CSS/interpolate-size
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#name
* https://developer.mozilla.org/en-US/docs/Web/CSS/::details-content
> [OP-198] Accordion Add Animation

- .storybook/preview.css
- package.json
- src/addons/fonts/material_symbols_outlined_variable.css
- src/components/accordion.css
- src/components/alert.css
- src/components/icon.css
- src/components/sidebar.css
- src/core/fonts/icon_fonts.css
- src/core/fonts/index.css
- src/stories/Components/Icon/Icon.js
- src/stories/Components/Icon/Icon.mdx
- src/stories/Components/Icon/Icon.stories.js
- src/stories/Overview/Addons.mdx
In order to improve the out of the box Optics experience as well as the ease of customizing icons, changes to how the component was built were needed. Additionally some performance improvements were made to reduce initial page load time
> [OP-195] Icon improvements

- .storybook/preview.css
- src/addons/fonts/feather_icons.css
- src/addons/fonts/lucide_icons.css
- src/addons/fonts/phosphor_icons.css
- src/addons/fonts/tabler_icons.css
- src/stories/Components/Icon/Icon.js
- src/stories/Components/Icon/Icon.mdx
- src/stories/Components/Icon/Icon.stories.js
- src/stories/Overview/Addons.mdx
There has been a desire to use icon libraries other than Material Symbols Outlined.
> [OP-28] Custom Icon Support

- package.json
- postcss.config.js
- yarn.lock
Even though the `dist` folder includes an `optics.min.css`, it wasn't actually minified. It was just a combined output.
> Minify CSS

- package.json
After the recent release, the addons folder was not being included
> Ensure distribution includes addons
