- README.md
- docs/token_structure.json
- package-lock.json
- package.json
- src/components/button.scss
- src/components/card.scss
- src/components/custom-tom-select.scss
- src/components/flash.scss
- src/components/form.scss
- src/components/icon.scss
- src/components/modal.scss
- src/components/panel.scss
- src/components/semantic_colors.scss
- src/components/sidebar.scss
- src/components/swatch.scss
- src/components/table.scss
- src/core/base.scss
- src/core/dynamic_color_engine.scss
- src/core/utilities.scss
- src/rolemodel-design-system.scss
- src/theme/base_theme.scss
- src/theme/dark_theme.scss
- src/theme/default_colors.scss
In effort to make this releasable, we want to take all our learnings and make them consistent here
> Various updates

- src/theme/base_theme.scss
> [GHI #17] Breakpoint values

- src/components/button.scss
- src/components/card.scss
- src/components/custom-tom-select.scss
- src/components/form.scss
- src/components/modal.scss
- src/components/panel.scss
- src/components/semantic_colors.scss
- src/components/sidebar.scss
- src/core/dynamic_color_engine.scss
- src/theme/dark_theme.scss
#15 
Adding new scale stops is not possible at the moment. With this pattern, we can adjust or add a new stop easier using a consistent naming convention.
> [GHI #15] Color Scales

- package-lock.json
- package.json
Update the package in prep for a release
> Prepare package for release

- README.md
https://github.com/RoleModel/rolemodel-design-system/issues/39
> [GHI #39] Install Instructions

- LICENSE
- README.md
https://github.com/RoleModel/rolemodel-design-system/issues/58
> [GHI #58] Add MIT License

- src/components/badge.scss
- src/components/index.scss
- src/stories/Badge.stories.js
- src/stories/Badge/Badge.js
- src/stories/Badge/Badge.mdx
#59 
This PR Addresses https://github.com/RoleModel/rolemodel-design-system/pull/19
> [GHI #59] Badges

- src/addons/rails-modal-and-panel/modal.scss
https://github.com/RoleModel/rolemodel-design-system/issues/62
> [GHI #62] Center modal class

- package-lock.json
- package.json
> Prep for release v0.0.8-beta

- package-lock.json
- package.json
- src/components/badge.scss
- src/components/button.scss
- src/components/card.scss
https://github.com/RoleModel/rolemodel-design-system/issues/77
> [GHI #77] Remove Placeholder Selectors

- .storybook/documentation.scss
- .storybook/preview.js
- src/components/button.scss
- src/components/index.scss
- src/components/navigation_rail.scss
- src/core/tokens/base_tokens.scss
- src/stories/LetterSpacing.stories.js
- src/stories/LetterSpacing/LetterSpacing.js
- src/stories/LetterSpacing/LetterSpacing.mdx
- src/stories/NavigationRail.stories.js
- src/stories/NavigationRail/NavigationRail.js
- src/stories/NavigationRail/NavigationRail.mdx
- src/stories/Transition.stories.js
- src/stories/Transition/Transition.js
- src/stories/Transition/Transition.mdx
https://github.com/RoleModel/rolemodel-design-system/issues/70
> [GHI #70] Sidebar Rail

- src/addons/tom-select.scss
- src/components/form.scss
- src/core/tokens/base_tokens.scss
> [GHI #85] Tom Select Single

- src/core/tokens/alert_color_tokens.scss
- src/core/tokens/dark_mode_tokens.scss
- src/core/tokens/scale_color_tokens.scss
https://github.com/RoleModel/rolemodel-design-system/issues/74
If any UI changes need to be shown off, please add screenshots here.
> [GHI #74] Alert Scales Dark Mode

- .storybook/documentation.scss
- src/components/badge.scss
- src/components/button.scss
- src/components/card.scss
- src/components/flash.scss
- src/components/table.scss
- src/core/base.scss
- src/stories/Badge/Badge.mdx
- src/stories/Button/Button.mdx
- src/stories/Card/Card.mdx
- src/stories/Flash/Flash.mdx
- src/stories/Table/Table.mdx
#89 
The API pattern for allowing overriding and customizing components was not documented well and was overly complicated. This aims to simplify the code and update documentation.
> [GHI #89] Api experiment again

- src/components/button.scss
> [GHI #94] Fix the button squish

- src/components/button_group.scss
- src/components/index.scss
- src/stories/ButtonGroup.stories.js
- src/stories/ButtonGroup/ButtonGroup.js
- src/stories/ButtonGroup/ButtonGroup.mdx
> [GHI #76] Add button group component

- src/components/form.scss
- src/core/tokens/base_tokens.scss
- src/stories/Form/Form.js
- src/stories/Form/Form.mdx
- src/stories/FormGroup.stories.js
- src/stories/Input.stories.js
#84 
#79 
Simplifying the checkbox and radio allows for adding indeterminate easily.
> [GHI #84 #79] Simplify checkbox and radio

- .github/pull_request_template.md
- package-lock.json
- package.json
- src/components/alert.scss
- src/components/index.scss
- src/core/tokens/alert_color_tokens.scss
- src/stories/Alert.stories.js
- src/stories/Alert/Alert.js
- src/stories/Alert/Alert.mdx
In order to have a standard way of displaying a warning, notice, banner, etc, we want to add an alert component.
> Alert component

- src/components/form.scss
- src/core/tokens/base_tokens.scss
- src/stories/Form/Form.js
- src/stories/Form/Form.mdx
#115 
The form styles are great, but we have had some simplifying ideas to make them easier to use
> [GHI #115] Forms Revisited

- package-lock.json
- package.json
- src/stories/1_Introduction.stories.mdx
> Prepare for v0.1.3-beta release

- package-lock.json
- package.json
- src/components/button.scss
- src/stories/Button/Button.mdx
#109 
The font variable names were incorrect
> [GHI #109] Button API Fix

- .github/workflows/release-package.yml
The build step is getting skipped which means the latest version doesn't have the dist folder...
> Add build step to workflow

- src/core/layout.scss
- src/stories/Recipes/CustomSidebar/CustomSidebar.js
- src/stories/Recipes/Layout/Layout.js
- src/stories/Recipes/Layout/Layout.mdx
- src/stories/Sidebar/Sidebar.js
#133 
Our layout classes were a bit confusing and leading to difficult naming when needing to override or modify.
> [GHI #133] Revise Layout classes

- .storybook/documentation.scss
- package.json
- src/addons/rails-modal-and-panel/modal.scss
- src/addons/rails-modal-and-panel/panel.scss
- src/components/button.scss
- src/components/flash.scss
- src/components/sidebar.scss
- src/core/tokens/base_tokens.scss
- src/stories/3_Tokens.stories.mdx
- src/stories/Animation.stories.js
- src/stories/Animation/Animation.js
- src/stories/Animation/Animation.mdx
- src/stories/InputHeight.stories.mdx
[TR #27](https://trello.com/c/wOBuyEcZ)
After recent design efforts and a complete Figma library, we want to ensure all our base tokens match what Figma is using.
> [TR#27] Revised Tokens

- package-lock.json
- package.json
- src/components/flash.scss
As part of  Release v0.3.0, the flash animation token was refactored, but the usage of it in the flash component was not updated.
> Fix token usage for flash

- src/components/badge.scss
- src/stories/Badge.stories.js
- src/stories/Badge/Badge.js
[TR #11](https://trello.com/c/Bz0hJzlk/11-badge)
Badges have been revised in Figma and our CSS needs to reflect that.
- ~~Do you need to update the package version?~~ Not until we have more components updated
> [TR#11] Update badge to reflect design

- .storybook/documentation.scss
- src/stories/Card/Card.js
[TR #18](https://trello.com/c/hbR8UmTC/18-card)
Update the card docs to better reflect usage.
> [TR#18] Card Revisions

- src/components/table.scss
[TR #115](https://trello.com/c/uH43JDy2)
An invalid token was being used.
> Table token bug

- src/stories/Overview/Tokens.mdx
[TR #116](https://trello.com/c/HcSBzGVa)
Add some documentation about token naming structure
> [TR#116] Token Naming Structure Docs

- .github/pull_request_template.md
- src/stories/Components/Alert/Alert.mdx
- src/stories/Components/Badge/Badge.mdx
- src/stories/Components/Button/Button.mdx
- src/stories/Components/ButtonGroup/ButtonGroup.mdx
- src/stories/Components/Card/Card.mdx
- src/stories/Components/ConfirmDialog/ConfirmDialog.mdx
- src/stories/Components/Form/Form.mdx
- src/stories/Components/Icon/Icon.mdx
- src/stories/Components/Sidebar/Sidebar.mdx
- src/stories/Components/Table/Table.mdx
- src/stories/Overview/SelectiveImports.mdx
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #119](https://trello.com/c/meNsbo76)
In order to add clarity on how components depend on each other, especially for people using selective imports, instructions need to be added into the documentation
In a specific component:
On the selective imports page:
> [TR#119] Import Instructions

- package-lock.json
- package.json
- src/components/index.scss
- src/components/tooltip.scss
- src/stories/Components/Tooltip/Tooltip.js
- src/stories/Components/Tooltip/Tooltip.mdx
- src/stories/Components/Tooltip/Tooltip.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
- tools/templates/component/??name??(pascalCase).mdx
[TR #93](https://trello.com/c/1JtzoxE7/93-tooltips)
Tooltips are a common pattern in applications for showing information on hover.
> [TR#93] Tooltips

- .gitignore
- .npmignore
- README.md
- optics-design-system.code-workspace
- src/components/avatar.scss
- src/components/index.scss
- src/stories/Components/Avatar/Avatar.js
- src/stories/Components/Avatar/Avatar.mdx
- src/stories/Components/Avatar/Avatar.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #9](https://trello.com/c/9MExcDwe)
For usage as profile pictures or settings links.
Hover State
Focus State
> [TR#9] Avatar

- src/components/divider.scss
- src/components/index.scss
- src/stories/Components/Divider/Divider.js
- src/stories/Components/Divider/Divider.mdx
- src/stories/Components/Divider/Divider.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #120]()
Dividers are a common pattern in applications for showing visual separation of content.
> [TR#120] Divider

- src/components/button.scss
- src/components/index.scss
- src/components/pagination.scss
- src/components/table.scss
- src/stories/Components/Button/Button.js
- src/stories/Components/Button/Button.mdx
- src/stories/Components/Pagination/Pagination.js
- src/stories/Components/Pagination/Pagination.mdx
- src/stories/Components/Pagination/Pagination.stories.js
- src/stories/Components/Table/Table.js
- src/stories/Components/Table/Table.mdx
- src/stories/Components/Table/Table.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #20](https://trello.com/c/fM0qvI8J)
Paginating data is a common pattern we want to support.
In the Table Docs
> [TR#20] Pagination

- src/recipes/16six-sidebar.scss
- src/recipes/domains-sidebar.scss
- src/stories/Components/Sidebar/Sidebar.js
- src/stories/Recipes/CustomSidebar/CustomSidebar.js
- src/stories/Recipes/CustomSidebar/CustomSidebar.mdx
After Updating the Sidebar in #160 , The Recipe Documentation showing how to customize it was left out of date and broken.
> Fix Sidebar Recipe Documentation

- src/components/form.scss
- src/components/index.scss
- src/components/toggle.scss
- src/stories/Components/Form/Form.js
- src/stories/Components/Form/Form.mdx
- src/stories/Components/Form/FormGroup.stories.js
- src/stories/Components/Toggle/Toggle.js
- src/stories/Components/Toggle/Toggle.mdx
- src/stories/Components/Toggle/Toggle.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
- tools/templates/component/??name??(pascalCase).mdx
[TR #15](https://trello.com/c/qH2thzjQ/15-toggle)
We’re currently using the Shoelace switch component when we reach for this pattern. It would be nice to have our own simple version of it.
> [TR#15] Toggle

- optics-design-system.code-workspace
Since we are enforcing declaration order and prettier linting, we want to make it easier to develop so we auto fix on save.
> Add rule to auto fix on save

- .storybook/documentation.scss
- src/components/index.scss
- src/components/tag.scss
- src/core/tokens/base_tokens.scss
- src/stories/Components/Badge/Badge.mdx
- src/stories/Components/Tag/Tag.js
- src/stories/Components/Tag/Tag.mdx
- src/stories/Components/Tag/Tag.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #10](https://trello.com/c/SZojNru1)
The codebase did not have this component so this PR adds it to closer align to Figma.
> [TR#10] Add tags component

- src/components/index.scss
- src/components/tab.scss
- src/stories/Components/Tab/Tab.js
- src/stories/Components/Tab/Tab.mdx
- src/stories/Components/Tab/Tab.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #13](https://trello.com/c/quw40pBb)
This needs to be developed to match the revised Figma component.
> [TR#13] Add tab component

- src/components/index.scss
- src/components/side_panel.scss
- src/core/layout.scss
- src/stories/Components/Alert/Alert.js
- src/stories/Components/Navbar/Navbar.js
- src/stories/Components/SidePanel/SidePanel.js
- src/stories/Components/SidePanel/SidePanel.mdx
- src/stories/Components/SidePanel/SidePanel.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- src/stories/Recipes/Layout/Layout.js
- src/stories/Recipes/Layout/Layout.mdx
- src/stories/Recipes/Layout/Layout.stories.js
- tools/generate-graph.dot
[TR #19](https://trello.com/c/RKaEKg10/19-side-panel)
Side Panels are a common use-case for various application needs
> [TR#19] Side Panel

- package-lock.json
- package.json
Bump version number in prep for release
> Version 0.5.0

- src/components/breadcrumbs.scss
- src/components/index.scss
- src/stories/Components/Breadcrumbs/Breadcrumbs.js
- src/stories/Components/Breadcrumbs/Breadcrumbs.mdx
- src/stories/Components/Breadcrumbs/Breadcrumbs.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #139](https://trello.com/c/m9cJzLfP/139-breadcrumbs-component)
A component for breadcrumbs would be nice.
Basically a nav group of links showing your navigation stack within the application.
> [TR#139] Breadcrumbs

- package-lock.json
- package.json
- src/components/breadcrumbs.scss
- src/components/index.scss
- src/components/text_pair.scss
- src/stories/Components/Breadcrumbs/Breadcrumbs.js
- src/stories/Components/Breadcrumbs/Breadcrumbs.mdx
- src/stories/Components/Breadcrumbs/Breadcrumbs.stories.js
- src/stories/Components/TextPair/TextPair.js
- src/stories/Components/TextPair/TextPair.mdx
- src/stories/Components/TextPair/TextPair.stories.js
- src/stories/Overview/assets/dependency-graph.svg
- tools/generate-graph.dot
[TR #146](https://trello.com/c/qFNaKUNX)
A title and subtitle pair has shown up as a common pattern desired. This aims to provide that along with an inline option to create a key value pattern.
> [TR#146] Text Pair

- package-lock.json
- package.json
Bump version number in prep for release
> Version 1.0.0!

- src/core/tokens/dark_mode_tokens.scss
- src/stories/Components/Accordion/Accordion.mdx
- src/stories/Components/Alert/Alert.mdx
- src/stories/Components/Avatar/Avatar.mdx
- src/stories/Components/Badge/Badge.mdx
- src/stories/Components/Breadcrumbs/Breadcrumbs.mdx
- src/stories/Components/Button/Button.mdx
- src/stories/Components/ButtonGroup/ButtonGroup.mdx
- src/stories/Components/Card/Card.mdx
- src/stories/Components/ConfirmDialog/ConfirmDialog.mdx
- src/stories/Components/Divider/Divider.mdx
- src/stories/Components/Form/Form.mdx
- src/stories/Components/Icon/Icon.mdx
- src/stories/Components/Modal/Modal.mdx
- src/stories/Components/Navbar/Navbar.mdx
- src/stories/Components/Pagination/Pagination.mdx
- src/stories/Components/SidePanel/SidePanel.mdx
- src/stories/Components/Sidebar/Sidebar.mdx
- src/stories/Components/Spinner/Spinner.mdx
- src/stories/Components/Switch/Switch.mdx
- src/stories/Components/Tab/Tab.mdx
- src/stories/Components/Table/Table.mdx
- src/stories/Components/Tag/Tag.mdx
- src/stories/Components/TextPair/TextPair.mdx
- src/stories/Components/Tooltip/Tooltip.mdx
- src/stories/Overview/ScaleOverriding.mdx
- src/stories/Recipes/CustomSidebar/CustomSidebar.mdx
- src/stories/Tokens/Typography/FontWeight.mdx
[RMD-358](https://linear.app/rolemodelsoftware/issue/RMD-358/optics-documentation-fixes)
Our current documentation for Optics has some refinements and fixes that could be made to help make it feel more consistent throughout. This includes using consistent capital case, resolving some typos, rephrasing some sentences to make it more clear to readers, and update links to external sites.
> RMD-358 optics documentation fixes (GH-239)

- package.json
- yarn.lock
> Update version and clean up yarn lock

- package.json
- src/components/alert.css
- src/components/alert.scss
- src/stories/Components/Alert/Alert.js
- src/stories/Components/Alert/Alert.mdx
In an effort to move away from sass, following a strict BEM structure in needed for Alerts.
- ~[ ] Have you updated any usage of changed tokens?~
- ~[ ] Have you updated the dependency graph with any component changes?~
> OP-173 Refactor Alert

- package.json
- src/components/navbar.css
- src/stories/Components/Navbar/Navbar.js
- src/stories/Components/Navbar/Navbar.mdx
[TR #182](https://linear.app/rolemodelsoftware/issue/OP-182/refactor-navbar)
In an effort to move away from SASS, updating the code and docs to follow a strict BEM structure is needed.
- ~[ ] Have you updated any usage of changed tokens?~
- ~[ ] Have you updated the dependency graph with any component changes?~
> [OP-182] Refactor Navbar

- src/stories/Overview/FileOrganization.mdx
Although, modeules does have a nice ring to it.
> Spell modules correctly

- package.json
> Bump version in prep for release

- .github/pull_request_template.md
The task link was outdated and the sanity check section needed some additional details
- ~~[ ] Did you add a component?~~
- ~~[ ] Have you added it to the dependency graph?~~
- ~~[ ] Have you added it to the docs?~~
- ~~[ ] Did you update a component?~~
- ~~[ ] Have you updated the dependency graph?~~
- ~~[ ] Have you updated the docs?~~
> Add more details and instructions to PR template
